name: Build Docker Image and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/livedata-backend-server

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create or Update Azure Container Instance
        run: |
          az container create --name livedata-backend-server --image ${{ secrets.DOCKER_HUB_USERNAME }}/livedata-backend-server --resource-group livedata --cpu 1 --memory 1.5 --registry-login-server docker.io --registry-username ${{ secrets.DOCKER_HUB_USERNAME }} --registry-password ${{ secrets.DOCKER_HUB_PASSWORD }} --dns-name-label livedata-backend-server --ports 8080 --no-wait || true

      - name: Restart Azure Container Instance
        run: |
          az container restart --name livedata-backend-server --resource-group livedata