name: Build Docker Image and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure using Managed Identity
        run: |
          az login --identity --username ${{ secrets.AZURE_CLIENT_ID }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Build and push
        run: |
          docker build -t youracr.azurecr.io/livedata-backend-server:latest .
          docker push youracr.azurecr.io/livedata-backend-server:latest
