name: Build Docker Image and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        run: |
          docker build -t espelund.azurecr.io/livedata-backend-server:latest .
          docker push espelund.azurecr.io/livedata-backend-server:latest
